=== tripnaught/tripnaught.github.io/recipes/recipe.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"required": [],
	"properties": {
		"slug": {
			"type": "string"
		},
		"title": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"yield": {
			"type": "string"
		},
		"ingredients": {
			"type": "array",
			"items": {"$ref": "#/$defs/ingredient"}
		},
		"steps": {
			"type": "array"
		},
		"notes": {
			"type": "array"
		}
	},
	"$defs": {
		"ingredient": {
			"type": "object",
			"properties": {
				"amount": {
					"type": "number"
				},
				"unit": {
					"type": "string"
				},
				"name": {
					"type": "string"
				},
				"notes": {
					"type": "string"
				}
			}
		}
	}
}

=== tripnaught/tripnaught.github.io/recipies/chocolate-chip-cookies.json
{
	"$schema": "./recipe.schema.json",
	"slug": "chocolate-chip-cookies",
	"title": "chocolate chip cookies",
	"ingredients": [
		{
			"amount": 1,
			"unit": "c",
			"name": "butter",
			"notes": "softened"
		},
		{
			"amount": 0.5,
			"unit": "c",
			"name": "white sugar"
		},
		{
			"amount": 0.5,
			"unit": "c",
			"name": "brown sugar"
		},
		{
			"amount": 2,
			"unit": "",
			"name": "eggs"
		},
		{
			"amount": 1,
			"unit": "tsp",
			"name": "vanilla extract"
		},
		{
			"amount": 1,
			"unit": "tsp",
			"name": "salt"
		},
		{
			"amount": 1,
			"unit": "tsp",
			"name": "baking soda"
		},
		{
			"amount": 2.5,
			"unit": "c",
			"name": "all-purpose flour"
		},
		{
			"amount": 2,
			"unit": "c",
			"name": "chocolate chips"
		}
	],
	"steps": [
		"Preheat oven to 350Â°F",
		"Cream together brown sugar, white sugar, and butter",
		"Add eggs and vanilla",
		"Combine flour, baking soda, and salt. Gradually stir into creamed mixture.",
		"Fold in chocolate chips.",
		"Using a scoop or rounded spoon, drop onto cookie sheet.",
		"Bake 8-10 minutes until light brown>"
	],
	"notes": []
}

=== tripnaught/tripnaught.github.io/recipes/oatmeal-cookies.json
{
	"$schema": "./recipe.schema.json",
	"slug": "vanishing-oatmeal-cookies",
	"title": "vanishing oatmeal cookies",
	"ingredients": [
		{
			"amount": 0.5,
			"unit": "c + 6 Tbsp",
			"name": "butter",
			"notes": "softened"
		},
		{
			"amount": 0.75,
			"unit": "c",
			"name": "brown sugar",
			"notes": "firmly packed"
		},
		{
			"amount": 0.5,
			"unit": "c",
			"name": "white granulated sugar"
		},
		{
			"amount": 2,
			"unit": "",
			"name": "eggs"
		},
		{
			"amount": 1,
			"unit": "tsp",
			"name": "vanilla extract"
		},
		{
			"amount": 1.5,
			"unit": "c",
			"name": "all-purpose flour"
		},
		{
			"amount": 1,
			"unit": "tsp",
			"name": "baking soda"
		},
		{
			"amount": 1,
			"unit": "tsp",
			"name": "ground cinnamon"
		},
		{
			"amount": 3,
			"unit": "c",
			"name": "rolled oats"
		},
		{
			"amount": 0.5,
			"unit": "tsp",
			"name": "salt",
			"notes": "optional"
		},
		{
			"amount": 1,
			"unit": "c",
			"name": "raisins",
			"notes": "if you're weird"
		}
	],
	"steps": [
		"Preheat oven to 350Â°F.",
		"Line baking sheet with parchment paper or silicone baking mat.",
		"Cream together butter, brown sugar, and white sugar.",
		"Add eggs and vanilla.",
		"Combine flour, baking soda, cinnamon, and salt. Gradually stir into creamed mixture.",
		"Add oats and raisins; mix well.",
		"Using a scoop or rounded spoon, drop onto cookie sheet.",
		"Bake 8-10 minutes or until light golden brown.",
		"Let cool 2-3 mins before moving to wire rack."
	],
	"notes": []
}

=== tripnaught/tripnaught.github.io/recipies/oatmeal-cookies.json
{
	"$schema": "./recipe.schema.json",
	"slug": "vanishing-oatmeal-cookies",
	"title": "vanishing oatmeal cookies",
	"ingredients": [
		{
			"amount": 0.825,
			"unit": "c",
			"name": "butter",
			"notes": "softened"
		},
		{
			"amount": 0.75,
			"unit": "c",
			"name": "brown sugar",
			"notes": "firmly packed"
		},
		{
			"amount": 0.5,
			"unit": "c",
			"name": "white granulated sugar"
		},
		{
			"amount": 2,
			"unit": "",
			"name": "eggs"
		},
		{
			"amount": 1,
			"unit": "tsp",
			"name": "vanilla extract"
		},
		{
			"amount": 1.5,
			"unit": "c",
			"name": "all-purpose flour"
		},
		{
			"amount": 1,
			"unit": "tsp",
			"name": "baking soda"
		},
		{
			"amount": 1,
			"unit": "tsp",
			"name": "ground cinnamon"
		},
		{
			"amount": 3,
			"unit": "c",
			"name": "rolled oats"
		},
		{
			"amount": 0.5,
			"unit": "tsp",
			"name": "salt",
			"notes": "optional"
		},
		{
			"amount": 1,
			"unit": "c",
			"name": "raisins",
			"notes": "if you're weird"
		}
	],
	"steps": [
		"Preheat oven to 350Â°F",
		"Cream together brown sugar, white sugar, and butter",
		"Add eggs and vanilla",
		"Combine flour, baking soda, and salt. Gradually stir into creamed mixture.",
		"Fold in chocolate chips.",
		"Using a scoop or rounded spoon, drop onto cookie sheet.",
		"Bake 8-10 minutes until light brown>"
	],
	"notes": []
}

=== tripnaught/tripnaught.github.io/recipes/ginger-molasses-cookies.json
{
	"$schema": "./recipe.schema.json",
	"slug": "ginger-molasses-cookies",
	"title": "copycat starbucks ginger molasses cookies",
	"ingredients": [
		{
			"amount": 2.25,
			"unit": "c",
			"name": "flour"
		},
		{
			"amount": 2,
			"unit": "tsp",
			"name": "baking soda"
		},
		{
			"amount": 0.25,
			"unit": "tsp",
			"name": "salt"
		},
		{
			"amount": 1,
			"unit": "tsp",
			"name": "ground ginger"
		},
		{
			"amount": 0.75,
			"unit": "c",
			"name": "unsalted butter",
			"notes": "softened"
		},
		{
			"amount": 1,
			"unit": "c",
			"name": "dark brown sugar"
		},
		{
			"amount": 1,
			"unit": "",
			"name": "egg"
		},
		{
			"amount": 1,
			"unit": "tsp",
			"name": "ground cinnamon"
		},
		{
			"amount": 0.25,
			"unit": "c",
			"name": "regular unsulphured molasses",
			"notes": "blackstrap is too strong"
		},
		{
			"name": "coarse granulated sugar",
			"notes": "for coating cookies before baking"
		}
	],
	"steps": [
		"Preheat oven to 375Â°F.",
		"Line baking sheet with parchment paper or silicone baking mat.",
		"Cream together butter & brown sugar in a mixer on high speed until light and fluffy.",
		"With mixer on medium speed, beat in egg & molasses, then increase speed to high and beat until well-mixed.",
		"Combine flour, baking soda, salt, cinnamon, and ginger. Mix into creamed batter at low speed.",
		"Use an cookie scoop or rounded spoon to form uniform balls of dough around 1\" in diameter, then roll into granulated sugar.",
		"Place on baking sheet (caution: cookies will spread when baking!)",
		"Bake for 12 mins, rotating halfway through."
	],
	"notes": []
}

=== tripnaught/tripnaught.github.io/recipes/recipe-template.json
{
	"$schema": "./recipe.schema.json",
	"slug": "recipe-name",
	"title": "recipe name",
	"ingredients": [
		{
			"amount": 1.5,
			"unit": "c",
			"name": "vanilla extract",
			"notes": "softened"
		},
		{
			"amount": 1.5,
			"unit": "c",
			"name": "vanilla extract"
		},
		{
			"amount": 1.5,
			"unit": "c",
			"name": "vanilla extract"
		},
		{
			"amount": 1.5,
			"unit": "c",
			"name": "vanilla extract"
		},
		{
			"amount": 1.5,
			"unit": "c",
			"name": "vanilla extract"
		},
		{
			"amount": 1.5,
			"unit": "c",
			"name": "vanilla extract"
		},
		{
			"amount": 1.5,
			"unit": "c",
			"name": "vanilla extract"
		},
		{
			"amount": 1.5,
			"unit": "c",
			"name": "vanilla extract"
		},
		{
			"amount": 1.5,
			"unit": "c",
			"name": "vanilla extract"
		},
		{
			"amount": 1.5,
			"unit": "c",
			"name": "vanilla extract"
		}
	],
	"steps": [
		"Preheat oven to 350°F",
		"Preheat oven to 350°F",
		"Preheat oven to 350°F",
		"Preheat oven to 350°F",
		"Preheat oven to 350°F",
		"Preheat oven to 350°F",
		"Preheat oven to 350°F",
		"Preheat oven to 350°F",
		"Preheat oven to 350°F"
	],
	"notes": []
}
